# Permalinks
permalink:        pretty

# Setup
title:            Donlelek
tagline:          things I do, things I like
url:              http://donlelek.github.io
paginate:         3
baseurl:          /
author:
  name:           Derek Price
  email:          dpricer@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/donlelek/donlelek.github.io/

# More
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
