# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Donlelek
tagline:          A personal blog
url:              http://donlelek.github.io
paginate:         1
baseurl:          /
author:
  name:           Derek Price
  email:          dpricer@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/donlelek/donlelek.github.io/
